In [1]:
import numpy as np

In [2]:
a = np.array([[[1,2,3,4],[5,6,7,8],[1,2,3,4],[5,6,7,8]],[[9,10,11,12],[13,14,15,16],[9,10,11,12],[13,14,15,16]]])

In [3]:
a

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

In [4]:
a.shape

(2, 4, 4)

In [5]:
b = a.reshape(2,4*4)

In [6]:
b

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16,  9, 10, 11, 12, 13, 14, 15, 16]])

In [7]:
b.shape

(2, 16)

In [8]:
c= b.reshape(-1,4,4)

In [9]:
c

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

In [10]:
c.shape

(2, 4, 4)

In [11]:
from sklearn.datasets import load_iris


In [12]:
iris = load_iris(as_frame=True)


In [19]:
iris.data.shape

(150, 4)

In [1]:
import torch

In [2]:
target = torch.LongTensor([1])


In [4]:
target[0]

tensor(1)