In [1]:
import numpy as np

In [2]:
# a = np.array([[[1,2,3,4],[5,6,7,8],[1,2,3,4],[5,6,7,8]],[[9,10,11,12],[13,14,15,16],[9,10,11,12],[13,14,15,16]]])

In [11]:
k = [1,2,3]
s = [4,5,6]
t = [7,8,9]
kk = [k,s,t]
kkk = [kk,kk,kk,kk]
kkkk = [kkk,kkk,kkk,kkk]

In [15]:
a = np.array(kkkk)

In [16]:
a

array([[[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]],


       [[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]],


       [[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]],


       [[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]]])

In [17]:
a.shape

(4, 4, 3, 3)

In [19]:
b = a.reshape(4,4*3*3)

In [20]:
b

array([[1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4,
        5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4,
        5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4,
        5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4,
        5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [21]:
b.shape

(4, 36)

In [22]:
c= b.reshape(-1,4,3,3)

In [23]:
c

array([[[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]],


       [[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]],


       [[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]],


       [[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]]])

In [24]:
c.shape

(4, 4, 3, 3)

In [11]:
from sklearn.datasets import load_iris


In [12]:
iris = load_iris(as_frame=True)


In [19]:
iris.data.shape

(150, 4)

In [1]:
import torch

In [2]:
target = torch.LongTensor([1])


In [4]:
target[0]

tensor(1)

In [1]:
#텐서 연산 테스트

In [2]:
import torch

In [3]:
output = torch.FloatTensor([[-0.2330,  0.4756,  0.1942,  0.1645, -0.2319, -0.2336,  0.4957,  0.8409,
          0.0472, -0.4364],
        [ 0.1710,  0.3710,  0.9478, -0.6706, -0.0231, -0.0650,  0.2580,  0.2889,
          0.1759, -0.5482],
        [ 0.1366,  0.5513,  0.6103, -0.6705, -0.5095, -0.3495, -0.1052,  0.2276,
          0.4141, -0.6761],
        [-0.1463,  0.2657,  0.4584,  0.1542,  0.1757,  0.0101,  0.9507,  1.0182,
         -0.1790, -0.3391]])

In [4]:
labels = torch.LongTensor([3, 5, 9, 9])

In [5]:
output

tensor([[-0.2330,  0.4756,  0.1942,  0.1645, -0.2319, -0.2336,  0.4957,  0.8409,
          0.0472, -0.4364],
        [ 0.1710,  0.3710,  0.9478, -0.6706, -0.0231, -0.0650,  0.2580,  0.2889,
          0.1759, -0.5482],
        [ 0.1366,  0.5513,  0.6103, -0.6705, -0.5095, -0.3495, -0.1052,  0.2276,
          0.4141, -0.6761],
        [-0.1463,  0.2657,  0.4584,  0.1542,  0.1757,  0.0101,  0.9507,  1.0182,
         -0.1790, -0.3391]])

In [6]:
output.size()

torch.Size([4, 10])

In [7]:
labels

tensor([3, 5, 9, 9])

In [8]:
def custom_CE(output,labels):
    count_output = len(labels)
    loss_total = 0.0
    for i in range(count_output):
        loss = torch.log(sum(torch.exp(output[i]))) - output[i][labels[i]]
        loss_total += loss
    return loss_total/count_output

In [9]:
print(custom_CE(output,labels))

tensor(2.7261)


In [10]:
def custom_CE(output,labels):
    count_output = len(labels)
    loss_total = 0.0
    for i in range(count_output):
        print(torch.log(sum(torch.exp(output[i]))))
    return loss_total/count_output

In [11]:
print(custom_CE(output,labels))

tensor(2.4877)
tensor(2.4883)
tensor(2.3719)
tensor(2.6407)
0.0


In [18]:
from torch.nn import functional as F

In [23]:
def custom_CE_tensor(output,labels):
    log_prob = -1.0 * F.log_softmax(output, 1)
    loss = log_prob.gather(1, labels.unsqueeze(1))
    loss = loss.mean()
    return loss

In [24]:
print(custom_CE_tensor(output,labels))

tensor(2.7261)


In [1]:
import torch

In [2]:
from torch.nn import functional as F

In [3]:
output = torch.FloatTensor([[-0.2330,  0.4756,  0.1942,  0.1645, -0.2319, -0.2336,  0.4957,  0.8409,
          0.0472, -0.4364],
        [ 0.1710,  0.3710,  0.9478, -0.6706, -0.0231, -0.0650,  0.2580,  0.2889,
          0.1759, -0.5482],
        [ 0.1366,  0.5513,  0.6103, -0.6705, -0.5095, -0.3495, -0.1052,  0.2276,
          0.4141, -0.6761],
        [-0.1463,  0.2657,  0.4584,  0.1542,  0.1757,  0.0101,  0.9507,  1.0182,
         -0.1790, -0.3391]])

In [4]:
labels = torch.LongTensor([3, 5, 9, 9])

In [5]:
logpt = F.log_softmax(output)


/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/ipykernel/__main__.py:1: UserWarning: Implicit dimension choice for log_softmax has been deprecated. Change the call to include dim=X as an argument.
  if __name__ == '__main__':


In [6]:
logpt.data

tensor([[-2.7207, -2.0121, -2.2935, -2.3232, -2.7196, -2.7213, -1.9920, -1.6468,
         -2.4405, -2.9241],
        [-2.3173, -2.1173, -1.5405, -3.1589, -2.5114, -2.5533, -2.2303, -2.1994,
         -2.3124, -3.0365],
        [-2.2353, -1.8206, -1.7616, -3.0424, -2.8814, -2.7214, -2.4771, -2.1443,
         -1.9578, -3.0480],
        [-2.7870, -2.3750, -2.1823, -2.4865, -2.4650, -2.6306, -1.6900, -1.6225,
         -2.8197, -2.9798]])

In [7]:
logpt

tensor([[-2.7207, -2.0121, -2.2935, -2.3232, -2.7196, -2.7213, -1.9920, -1.6468,
         -2.4405, -2.9241],
        [-2.3173, -2.1173, -1.5405, -3.1589, -2.5114, -2.5533, -2.2303, -2.1994,
         -2.3124, -3.0365],
        [-2.2353, -1.8206, -1.7616, -3.0424, -2.8814, -2.7214, -2.4771, -2.1443,
         -1.9578, -3.0480],
        [-2.7870, -2.3750, -2.1823, -2.4865, -2.4650, -2.6306, -1.6900, -1.6225,
         -2.8197, -2.9798]])

In [8]:
loss = logpt.gather(1, labels.unsqueeze(1))


In [9]:
loss

tensor([[-2.3232],
        [-2.5533],
        [-3.0480],
        [-2.9798]])

In [10]:
a = loss.exp()

In [11]:
a

tensor([[0.0980],
        [0.0778],
        [0.0475],
        [0.0508]])

In [16]:
loss = loss.view(-1)

In [17]:
loss

tensor([-2.3232, -2.5533, -3.0480, -2.9798])

In [18]:
loss.exp()

tensor([0.0980, 0.0778, 0.0475, 0.0508])

In [4]:
output.size()

torch.Size([4, 10])

In [26]:
def custom_FL(output,labels, alpha=0.25, gamma=2):
    count_output = len(labels)
    loss_total = 0.0
    for i in range(count_output):
        pt = torch.exp(output[i][labels[i]])/sum(torch.exp(output[i]))
        loss = -1*alpha*((1-pt)**gamma)*(torch.log(pt))
        print(loss)
        loss_total += loss
    return loss_total/count_output

In [27]:
def custom_FL_tensor(output,labels, alpha=0.25, gamma=2):
    logpt = F.log_softmax(output, 1)
    logpt = logpt.gather(1, labels.unsqueeze(1))
    logpt = logpt.view(-1)
    pt = logpt.exp()
    loss = -1*alpha*((1-pt)**gamma)*logpt
    loss = loss.mean()
    return loss

In [28]:
print(custom_FL(output, labels))

tensor(0.4726)
tensor(0.5428)
tensor(0.6914)
tensor(0.6712)
tensor(0.5945)


In [29]:
print(custom_FL_tensor(output, labels))

tensor([0.4726, 0.5428, 0.6914, 0.6712])
tensor(0.5945)


In [10]:
!nvidia-smi

Mon Aug  2 15:24:44 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 418.67       Driver Version: 418.67       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla V100-SXM2...  On   | 00000000:00:05.0 Off |                  Off |
| N/A   38C    P0    76W / 300W |   5954MiB / 32480MiB |     75%      Default |
+-------------------------------+----------------------+----------------------+
|   1  Tesla V100-SXM2...  On   | 00000000:00:06.0 Off |                  Off |
| N/A   43C    P0    75W / 300W |   5922MiB / 32480MiB |     63%      Default |
+-------------------------------+----------------------+----------------------+
        